server:
  port: 18081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  application:
    name: user-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka # EurekaServer的地址
  instance:
#    指定访问的ip地址
    ip-address: 127.0.0.1
    prefer-ip-address: true
#   租约续订间隔时间（默认30秒），如下所示每间隔 5s 向服务端发送一次心跳，证明自己依然"存活"
    lease-renewal-interval-in-seconds: 5
#   租约到期时间（默认90秒），如下所示，告诉服务端如果我 10s 之内没有给你发心跳，就代表我"死"了，将我踢出掉
    lease-expiration-duration-in-seconds: 15

test:
  msg: hello,github!哈喽
